name: Clojure CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@10.1
      with:
        # Install just one or all simultaneously
        # The value must indicate a particular version of the tool, or use 'latest'
        # to always provision the latest version
        lein: 2.9.8                  # Leiningen
        clj-kondo: 2022.05.31        # Clj-kondo
        cljstyle: 0.15.0             # cljstyle
        zprint: 1.2.3                # zprint
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
